spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.168.98.210:3306/dataSync?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimeZone=GMT%2B8
    username: root
    password: 123456
  rabbitmq:
    host: 10.168.98.210
    username: admin
    password: admin
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
    virtual-host: my_vhost

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl